services:
    postgres:
        image: aliasvault-postgres
        build:
            context: .
            dockerfile: apps/server/Databases/AliasServerDb/Dockerfile

    client:
        image: aliasvault-client
        build:
            context: .
            dockerfile: apps/server/AliasVault.Client/Dockerfile

    api:
        image: aliasvault-api
        build:
            context: .
            dockerfile: apps/server/AliasVault.Api/Dockerfile

    admin:
        image: aliasvault-admin
        build:
            context: ../
            dockerfile: ../apps/server/AliasVault.Admin/Dockerfile

    reverse-proxy:
        image: aliasvault-reverse-proxy
        build:
            context: ../
            dockerfile: ../apps/server/Dockerfile

    smtp:
        image: aliasvault-smtp
        build:
            context: ../
            dockerfile: ../apps/server/Services/AliasVault.SmtpService/Dockerfile

    task-runner:
        image: aliasvault-task-runner
        build:
            context: ../
            dockerfile: ../apps/server/Services/AliasVault.TaskRunner/Dockerfile
